/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryfix;
import java.sql.Connection;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author rizky
 */
public class Tfrom4 extends javax.swing.JFrame {

    private String tgl;

    /**
     * Creates new form Tfrom4
     */
    public Tfrom4() {
        initComponents();
        tbl_transaksi();
        kosong();
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tbl_Transaksi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtNoHP = new javax.swing.JTextField();
        txtberat = new javax.swing.JTextField();
        Ttl_Harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tambah = new javax.swing.JButton();
        txttanggal = new javax.swing.JTextField();
        txtjeniscuci = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tbl_Transaksi.setBackground(new java.awt.Color(0, 153, 153));
        Tbl_Transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("History Transaksi Laundry Express");
        Tbl_Transaksi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 19, -1, 30));

        txttabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        txttabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txttabel);

        Tbl_Transaksi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 79, 873, 96));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 401, 64, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 401, -1, -1));

        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, 30));

        jButton5.setText("Simpan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 30));

        jLabel2.setText("Username");
        Tbl_Transaksi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 201, -1, -1));

        jLabel3.setText("alamat");
        Tbl_Transaksi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel5.setText("NoHP");
        Tbl_Transaksi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 30, 20));

        jLabel6.setText("berat");
        Tbl_Transaksi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel7.setText("bayar");
        Tbl_Transaksi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        jLabel8.setText("harga");
        Tbl_Transaksi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 194, -1, 30));
        Tbl_Transaksi.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, -1));

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, -1));
        Tbl_Transaksi.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 150, -1));

        txtNoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHPActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(txtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 150, -1));

        txtberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(txtberat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 150, -1));

        Ttl_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ttl_HargaActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(Ttl_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 150, -1));

        jLabel4.setText("tanggal");
        Tbl_Transaksi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        Tambah.setText("Ubah Data Input");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 30));
        Tbl_Transaksi.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 150, -1));

        txtjeniscuci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjeniscuciActionPerformed(evt);
            }
        });
        Tbl_Transaksi.add(txtjeniscuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 150, -1));

        jLabel9.setText("jeniscuci");
        Tbl_Transaksi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 20));

        getContentPane().add(Tbl_Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void kosong(){
    txtusername.setEditable(true);
        txtusername.setText(null);
        txtalamat.setText(null);
        txtjeniscuci.setText(null);
        txtberat.setText(null);
        Ttl_Harga.setText(null);
        txtBayar.setText(null);
        txttanggal.setText(null);
        txtNoHP.setText(null);
    }
    private void txttabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttabelMouseClicked
        int baris = txttabel.rowAtPoint(evt.getPoint());
        String username = txttabel.getValueAt(baris, 1).toString();
        txtusername.setText(username);
        String alamat = txttabel.getValueAt(baris, 2).toString();
        txtalamat.setText(alamat);
        String jeniscuci = txttabel.getValueAt(baris, 3).toString();
        txtjeniscuci.setText(jeniscuci);
        String  berat = txttabel.getValueAt(baris, 4).toString();
        txtberat.setText(berat);
        String  Harga = txttabel.getValueAt(baris, 5).toString();
        Ttl_Harga.setText(Harga);
        String  Bayar = txttabel.getValueAt(baris, 6).toString();
        txtBayar.setText(Bayar);
        String  tanggal = txttabel.getValueAt(baris, 7).toString();
        txttanggal.setText(tanggal);
        String HP = txttabel.getValueAt(baris,8).toString();
        txtNoHP.setText(HP);
        
         
    }//GEN-LAST:event_txttabelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
            Tfrom3 from = new Tfrom3();
            from.show();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       try {
            String sql ="delete from login where username='"+txtusername.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus data ini ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);JOptionPane.showMessageDialog(this, "berhasil di hapus");
       }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        
        tbl_transaksi();
        kosong();
                 } 
    
    }//GEN-LAST:event_hapusActionPerformed
       
    private void txtNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHPActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                              
     
        try{
             String sql = "INSERT INTO login VALUES ('"+txtusername.getText()+"', '"+txtalamat.getText()+"', '"+txtjeniscuci.getText()+"', '"+txtberat.getText()+"', '"+Ttl_Harga.getText()+"', '"+txtBayar.getText()+"', '"+txttanggal.getText()+"', '"+txtNoHP.getText()+"')";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Berhasil");
            tbl_transaksi();
            kosong();
           
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_TambahActionPerformed

    private void txtjeniscuciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjeniscuciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjeniscuciActionPerformed

    private void Ttl_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ttl_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ttl_HargaActionPerformed
    
    
    private void tbl_transaksi(){
 try {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn ("NO");
        model.addColumn ("username");
        model.addColumn ("alamat");
        model.addColumn ("jeniscuci");
        model.addColumn ("berat");
        model.addColumn ("Harga");
        model.addColumn ("Bayar");
        model.addColumn ("tanggal");
        model.addColumn ("HP");
        
          int no=1;
          String sql= " select * from login";
          java.sql.Connection conn=(Connection)Config.configDB();
          java.sql.Statement stm=conn.createStatement();
          java.sql.ResultSet res=stm.executeQuery(sql);
        
          while (res.next()){

              model.addRow(new Object[]{no++, res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});
        }
        txttabel.setModel(model);
        } catch (Exception e) {
        }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tfrom4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tfrom4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tfrom4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tfrom4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tfrom4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tambah;
    private javax.swing.JPanel Tbl_Transaksi;
    private javax.swing.JTextField Ttl_Harga;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtNoHP;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txtjeniscuci;
    private javax.swing.JTable txttabel;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}


